spring:
  jackson:
    default-property-inclusion: non_null # Exclude null properties from JSON serialization
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:mysql://localhost:13306/survey?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 50    # Batch insert size
        format_sql: true
        show_sql: true
    open-in-view: false
logging:
  level:
    # JdbcTemplate 의 쿼리 실행 로그를 DEBUG 레벨로 찍음
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    # 바인딩된 파라미터 값을 TRACE 레벨로 찍음
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
