### Create a new form
POST http://localhost:8080/api/v1/forms
Content-Type: application/json

{
  "title": "티셔츠 신청",
  "description": "티셔츠를 신청하려면 이름 및 사이즈를 입력하세요.",
  "questions": [
    {
      "title": "티셔츠 사이즈",
      "description": "",
      "type": "RADIO",
      "required": false,
      "version": 0,
      "selectableOptions": [
        {
          "text": "XS"
        },
        {
          "text": "S"
        }
      ]
    }
  ]
}

> {%
    // Location 헤더 전체를 가져오기
    const location = response.headers.valueOf("Location");
    // URL 마지막 슬래시 뒤의 formId만 추출
    const formId = location.substring(location.lastIndexOf('/') + 1);
    // 전역 변수로 저장
    client.global.set('formId', formId);
    client.log("Saved formId: " + formId);
%}

### Get Form by ID
GET http://localhost:8080/api/v1/forms/{{formId}}
Accept: application/json

> {%
    console.log(`headers: ${JSON.stringify(request.headers.all())}`)
    console.log(`request body: ${JSON.stringify(request.body)}`)
%}

### Update Form by ID
PUT http://localhost:8080/api/v1/forms/{{formId}}
Content-Type: application/json

{
  "title": "티셔츠 신청 (수정)",
  "description": "티셔츠를 신청하려면 이름 및 사이즈를 입력하세요. (수정됨)",
  "questions": [
    {
      "questionTemplateId": "01JY4AZT4Q1KB5CA766CJZ9TF0",
      "title": "티셔츠 사이즈 2 (수정됨)",
      "description": "",
      "type": "TEXT",
      "required": false,
      "selectableOptions": []    }
  ]
}

### Reply to Form
POST http://localhost:8080/api/v1/forms/{{formId}}/submit
Content-Type: application/json

[
    {
        "questionTemplateId": "01JY3JP6M29X4ZW8KDD268H7GK",
        "answer": "",
        "selectableOptionIds": [
          "01JY3JP6M5QFJ5HCYNY51YAD4V"
        ]
    }
]
