### Create a new form
POST http://localhost:8080/api/v1/forms
Content-Type: application/json

{
  "title": "티셔츠 신청",
  "description": "티셔츠를 신청하려면 이름 및 사이즈를 입력하세요.",
  "questions": [
    {
      "title": "이름",
      "description": "반드시 본명을 입력해주세요.",
      "type": "TEXT",
      "required": true,
      "version": 0,
      "selectableOptions": []
    },
    {
      "title": "티셔츠 사이즈",
      "description": "",
      "type": "RADIO",
      "required": false,
      "version": 0,
      "selectableOptions": [
        {
          "text": "XS"
        },
        {
          "text": "S"
        },
        {
          "text": "M"
        },
        {
          "text": "L"
        },
        {
          "text": "XL"
        }
      ]
    },
    {
      "title": "기타 의견",
      "description": "",
      "type": "LONG_TEXT",
      "required": false,
      "version": 0,
      "selectableOptions": []
    }
  ]
}

> {%
    // Location 헤더 전체를 가져오기
    const location = response.headers.valueOf("Location");
    // URL 마지막 슬래시 뒤의 formId만 추출
    const formId = location.substring(location.lastIndexOf('/') + 1);
    // 전역 변수로 저장
    client.global.set('formId', formId);
    client.log("Saved formId: " + formId);
%}

### Get Form by ID
GET http://localhost:8080/api/v1/forms/{{formId}}
Accept: application/json

> {%
    console.log(`headers: ${JSON.stringify(request.headers.all())}`)
    console.log(`request body: ${JSON.stringify(request.body)}`)
%}

### Update Form by ID
PUT http://localhost:8080/api/v1/forms/{{formId}}
Content-Type: application/json

{
  "title": "티셔츠 신청 (수정)",
  "description": "티셔츠를 신청하려면 이름 및 사이즈를 입력하세요. (수정됨)",
  "questions": [
    {
      "questionTemplateId": "01JY1MKEQS1B1HRV4BGSG8NB3V",
      "title": "귀하의 신장은 몇 cm인가요?",
      "description": "",
      "type": "CHECKBOX",
      "required": false
    }
  ]
}
