spring:
  application:
    name: onboarding-project

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # Kotlin + Spring 호환 이슈 방지 (Spring Boot 2.x 기준)

  jackson:
    property-naming-strategy: SNAKE_CASE   # JSON 응답 시 snake_case 적용 (선택)

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080