spring:
  application:
    name: onboarding
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:onboarding
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true