spring:
  application:
    name: taehyung-onboarding

  datasource:
    hikari:
        jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;
        driver-class-name: org.h2.Driver
        username: sa
        password: