spring:
  application:
    name: baul-onboarding
  datasource:
    url: jdbc:h2:mem:onboarding
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  sql:
    init:
      mode: always
      schema-locations: classpath:static/sql/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 8888
