server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3037/fastcampusdb  # fastcampusdb 사용
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL8Dialect 대신 MySQLDialect 사용
    open-in-view: false

