spring:
  application:
    name: survey-service

  # 데이터소스 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console

# 서버 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.innercircle: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

# API 문서 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
