server:
  port: 9991
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /survey-service/api

spring:
  application:
    name: survey-service

  datasource:
    url: jdbc:h2:mem:survey
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    com.okdori.surveyservice: DEBUG
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type: DEBUG
