server:
  port: 8080
spring:
  application:
    name: survey-service
  datasource:
    url: jdbc:h2:mem:survey
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2:
    console:
        enabled: true
        path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
