spring:
  datasource:
    url: jdbc:h2:mem:survey
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true           # H2 ? ?? ???
      path: /h2-console       # H2 ?? ?? ??
  jpa:
    hibernate:
      ddl-auto: update        # create, update, none ? ??
    show-sql: true            # SQL ?? ??
    properties:
      hibernate:
        format_sql: true      # SQL ??? ??
