spring:
  datasource:
    url: 'jdbc:h2:mem:querybox'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

    console:
      enabled: true
      path: '/h2-console'


  springdoc:
    swagger-ui:
      path: /swagger-ui.html